name: docker

on:
  schedule:
    - cron: '0 18 * * *'
  push:
    branches:
      - 'v[0-9]+.*'
    paths-ignore:
      - '.gitignore'
      - '**.md'

jobs:
  docker:
    name: build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Compute tag
        id: tag
        run: |
          [[ "${{ github.event_name }}" == "push" ]] && \
            echo "::set-output name=tag::$(cut -d/ -f3 <<< ${{ github.ref }})" || \
            echo "::set-output name=tag::nightly"
        shell: bash
      - name: Build image
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/nebula-console:${{ steps.tag.outputs.tag }}
        run: |
          docker build -t ${IMAGE_NAME} .
          docker push ${IMAGE_NAME}
        shell: bash
